# Generated by Django 6.0.2 on 2026-03-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('REGISTER_REMINDER', 'แจ้งเตือนก่อนกิจกรรม (ผู้สมัคร)'), ('SAVED_REMINDER', 'แจ้งเตือนก่อนกิจกรรม (ผู้บันทึก)'), ('OWNER_STATUS_REMINDER', 'แจ้งเตือนสถานะผู้สมัคร (ผู้สร้างกิจกรรม)'), ('OWNER_FULL', 'แจ้งเตือนกิจกรรมเต็ม (ผู้สร้างกิจกรรม)'), ('SAVED_FULL', 'แจ้งเตือนกิจกรรมเต็ม (ผู้บันทึก)'), ('POST_UPDATED', 'แจ้งเตือนเมื่อโพสต์มีการเปลี่ยนแปลง'), ('POST_DELETED', 'แจ้งเตือนเมื่อโพสต์ถูกลบ'), ('POST_HIDDEN', 'แจ้งเตือนเมื่อโพสต์ถูกซ่อน'), ('FOLLOWER_NEW_POST', 'แจ้งเตือนเมื่อคนที่ติดตามโพสต์ใหม่'), ('CHAT_MESSAGE', 'แจ้งเตือนข้อความแชทใหม่'), ('SYSTEM', 'ระบบ')], default='SYSTEM', max_length=40),
        ),
    ]
